// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qH6fje03t0jDkoJFrDunXeYQN_UAhfM',
    appId: '1:462994057245:web:2a34a67b97d912c153fef4',
    messagingSenderId: '462994057245',
    projectId: 'smart-irrigation-system-23802',
    authDomain: 'smart-irrigation-system-23802.firebaseapp.com',
    databaseURL: 'https://smart-irrigation-system-23802-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-system-23802.firebasestorage.app',
    measurementId: 'G-8NTEGF2WCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6EL-ra_Z803Sj-qcZPI-kpz8p2UmwpKE',
    appId: '1:462994057245:android:26c6314f9ba399af53fef4',
    messagingSenderId: '462994057245',
    projectId: 'smart-irrigation-system-23802',
    databaseURL: 'https://smart-irrigation-system-23802-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-system-23802.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOyqKRlHeQgmqtUmxuuSL9HXRLXXJm6Nw',
    appId: '1:462994057245:ios:70426a55c3e7979653fef4',
    messagingSenderId: '462994057245',
    projectId: 'smart-irrigation-system-23802',
    databaseURL: 'https://smart-irrigation-system-23802-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-system-23802.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOyqKRlHeQgmqtUmxuuSL9HXRLXXJm6Nw',
    appId: '1:462994057245:ios:70426a55c3e7979653fef4',
    messagingSenderId: '462994057245',
    projectId: 'smart-irrigation-system-23802',
    databaseURL: 'https://smart-irrigation-system-23802-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-system-23802.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7qH6fje03t0jDkoJFrDunXeYQN_UAhfM',
    appId: '1:462994057245:web:7c79e53635e39b6453fef4',
    messagingSenderId: '462994057245',
    projectId: 'smart-irrigation-system-23802',
    authDomain: 'smart-irrigation-system-23802.firebaseapp.com',
    databaseURL: 'https://smart-irrigation-system-23802-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-irrigation-system-23802.firebasestorage.app',
    measurementId: 'G-F5BPNNWSP6',
  );
}
